"""
Target-node difficulty (hardness) analysis.

This script answers the reviewer request:

    "It would be useful to analyse performance by simple node-level characteristics,
     such as: degree; internal versus external connections; centrality; embeddedness
     in the original community; community size."

For every detection algorithm in ``DETECTION_ALGS`` we:

1.  Build (or load from cache) the community partition of the *original* graph
    produced by that algorithm.  Partitions are cached at
    ``outputs_review/hardness/{dataset}/partitions/{algorithm}.json`` so they are
    computed only once.  If the file already exists it is reused, otherwise it is
    generated by applying the algorithm to the graph and saved.
2.  Compute, for every target node, a set of node-level "difficulty" features,
    some of them relative to the node's *original* community in that partition:
        - degree                       (global)
        - betweenness/eigenvector/pagerank centrality   (global, from feature_analysis CSVs)
        - internal_degree / external_degree / internal_ratio   (internal vs external)
        - embeddedness  (within-community local clustering)     (embeddedness)
        - participation_coef                                    (extra embeddedness measure)
        - community_size                                        (community size)
3.  Join those features with the per-target-node outcome (success rate, i.e. the
    ``goal`` field, 1 = node successfully hidden) of every evasion method, pooled
    across seeds and budget factors.
4.  Produce difficulty curves (per-dataset, pooled-per-algorithm across datasets,
    and fully pooled): success rate vs a three-group split of each feature, one
    line per method. One PDF per feature is written directly into the detection
    algorithm's main directory. The groups are:
        - community_size                : Small / Medium / Big (always three sizes)
        - every other feature           : Low (0-70%), Medium (70-90%), High (90-100%)
          where the cut points refer to the node's percentile rank for that feature.

All artefacts are written under ``outputs_review/hardness/``.

Run from the repository root, e.g.::

    python -m src.utils.node_hardness_analysis
    python -m src.utils.node_hardness_analysis --datasets kar words --algs greedy leiden
"""

from __future__ import annotations

import argparse
import json
import os
from typing import Dict, List, Optional

import igraph as ig
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns


# ----------------------------------------------------------------------------- #
#                                CONFIGURATION                                  #
# ----------------------------------------------------------------------------- #

# Repository root (this file lives in <root>/src/utils/)
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

RUNS_DIR = os.path.join(ROOT_DIR, "outputs_review", "runs")
FEATURE_DIR = os.path.join(ROOT_DIR, "outputs_review", "feature_analysis")
NETWORKS_DIR = os.path.join(ROOT_DIR, "dataset", "networks")
OUT_DIR = os.path.join(ROOT_DIR, "outputs_review", "hardness")

# Datasets: directory/file name -> enum-style KEY used by DGCluster.
DATASET_KEYS: Dict[str, str] = {
    "kar": "KAR",
    "words": "WORDS",
    "vote": "VOTE",
    "pow": "POW",
    "fb-75": "FB_75",
    "cond-mat": "COND_MAT",
}
DATASETS: List[str] = list(DATASET_KEYS.keys())

# Detection algorithms whose partition (and outcomes) we analyse.
DETECTION_ALGS: List[str] = ["greedy", "leiden", "walktrap", "dgcluster"]

# Evasion methods: display name -> json_results file stem.
METHOD_FILE: Dict[str, str] = {
    "NABLA": "nabla-cmh",
    "NABLAP": "nabla-cmh-projected",
    "DRL": "drl-agent",
    "DICE": "dice",
    "ROAM": "roam",
    "RAND": "random",
    "DEG": "degree",
    "BETW": "betweenness",
}
# Pretty names / palette (consistent with notebooks/plot_all_datasets.ipynb).
METHOD_RENAME: Dict[str, str] = {
    "NABLA": r"$\nabla$-CMH (ours)",
    "NABLAP": r"$\nabla$-CMH-P",
    "DRL": "DRL-Agent",
    "DICE": "DICE",
    "ROAM": "ROAM",
    "RAND": "Random",
    "DEG": "Degree",
    "BETW": "Centrality",
}
METHOD_PALETTE: Dict[str, str] = {
    r"$\nabla$-CMH (ours)": "#1019C7",
    r"$\nabla$-CMH-P": "#5B61D6",
    "DRL-Agent": "#0AAEC3",
    "DICE": "#018E20",
    "ROAM": "#96AD11",
    "Random": "#DE8D00",
    "Degree": "#B40F00",
    "Centrality": "#8F00A2",
}
METHOD_ORDER: List[str] = [METHOD_RENAME[m] for m in
                           ["NABLA", "NABLAP", "DRL", "DICE", "ROAM", "RAND", "DEG", "BETW"]]

SEEDS: List[int] = [22, 2025, 42]
BETAS: List[float] = [0.5, 1, 2]
TAU: float = 0.5
# Seed used to (re)generate stochastic partitions (leiden / dgcluster). Matches the
# default ExperimentHyps.seed used in the experiments.
PARTITION_SEED: int = 2025

# Features analysed and the reviewer characteristic each maps to.
# (key, pretty label).  The first five are the reviewer's list; the rest are extras
# left in the master table so a co-author can pick alternatives.
REVIEWER_FEATURES: List[tuple] = [
    ("degree", "Degree"),
    ("internal_ratio", "Internal-edge fraction"),
    ("betweenness_centrality", "Betweenness centrality"),
    ("embeddedness", "Embeddedness (intra-clustering)"),
    ("community_size", "Community size"),
]
EXTRA_FEATURES: List[tuple] = [
    ("eigenvector_centrality", "Eigenvector centrality"),
    ("pagerank", "PageRank"),
    ("internal_degree", "Internal degree"),
    ("external_degree", "External degree"),
    ("participation_coef", "Participation coefficient"),
]

# Three-group split used by the difficulty curves.
#   - non-community-size features: percentile-rank groups.
#   - community size: direct Small / Medium / Big (always three sizes).
PCT_BIN_EDGES = [0.0, 0.7, 0.9, 1.0]
PCT_BIN_LABELS = ["Low\n(0-70%)", "Medium\n(70-90%)", "High\n(90-100%)"]
COMM_SIZE_LABELS = ["Small", "Medium", "Big"]

# Colours for the per-feature lines in the NABLA-only overview plot.
FEATURE_LINE_COLORS = ["#1019C7", "#018E20", "#DE8D00", "#8F00A2", "#B40F00",
                       "#0AAEC3", "#96AD11", "#4B4D52", "#E377C2", "#7F7F7F"]


def check_dir(path: str) -> None:
    """Create ``path`` if it does not exist."""
    if not os.path.exists(path):
        os.makedirs(path)


# ----------------------------------------------------------------------------- #
#                              GRAPH / PARTITIONS                               #
# ----------------------------------------------------------------------------- #

def import_graph(dataset: str) -> ig.Graph:
    """
    Load the graph exactly like ``Utils.import_graph``: relabel the sorted unique
    node ids to ``0..n-1`` (so node ids match the feature CSVs and the stored
    ``target_node`` ids) and keep the original ids in the ``name`` attribute.
    """
    file_path = os.path.join(NETWORKS_DIR, f"{dataset}.txt")
    with open(file_path, "r") as f:
        edges = [tuple(map(int, line.split())) for line in f if line.strip()]
    unique_nodes = sorted({n for e in edges for n in e})
    mapping = {old: new for new, old in enumerate(unique_nodes)}
    relabeled = [(mapping[a], mapping[b]) for a, b in edges]
    graph = ig.Graph(edges=relabeled, directed=False)
    graph.vs["name"] = unique_nodes
    return graph


def _compute_partition(graph: ig.Graph, dataset: str, alg: str) -> List[List[int]]:
    """Run ``alg`` on ``graph`` and return communities as a list of node-id lists."""
    if alg == "greedy":
        clustering = graph.community_fastgreedy().as_clustering()
        return [list(c) for c in clustering]
    if alg == "walktrap":
        clustering = graph.community_walktrap().as_clustering()
        return [list(c) for c in clustering]
    if alg == "leiden":
        import leidenalg as la
        part = la.find_partition(graph, la.ModularityVertexPartition, seed=PARTITION_SEED)
        return [list(c) for c in part]
    if alg == "dgcluster":
        # Heavy path: needs torch + the pre-trained model. Imported lazily so the
        # other algorithms work without a torch install.
        import sys
        if ROOT_DIR not in sys.path:
            sys.path.insert(0, ROOT_DIR)
        from src.community_detection.extra_algs.dgcluster.dgcluster import DGCluster
        node_clustering = DGCluster(graph, DATASET_KEYS[dataset])
        return [list(c) for c in node_clustering.communities]
    raise ValueError(f"Unknown detection algorithm: {alg}")


def get_partition(dataset: str, alg: str, graph: ig.Graph) -> List[List[int]]:
    """
    Return the cached partition for ``(dataset, alg)`` or compute, cache and return it.

    Cache file: ``outputs_review/hardness/{dataset}/partitions/{alg}.json`` storing
    ``{"algorithm", "dataset", "n_nodes", "seed", "communities": [[...], ...]}``.
    """
    cache_dir = os.path.join(OUT_DIR, dataset, "partitions")
    cache_path = os.path.join(cache_dir, f"{alg}.json")
    if os.path.exists(cache_path):
        with open(cache_path, "r") as f:
            return json.load(f)["communities"]

    print(f"  [partition] generating {alg} for {dataset} ...")
    communities = _compute_partition(graph, dataset, alg)
    # Cast to native python ints (some algorithms return numpy int ids) for JSON.
    communities = [[int(v) for v in c] for c in communities]
    check_dir(cache_dir)
    # Serialize first so a serialization error never leaves a truncated cache file.
    payload = json.dumps(
        {
            "algorithm": alg,
            "dataset": dataset,
            "n_nodes": graph.vcount(),
            "seed": PARTITION_SEED if alg in ("leiden", "dgcluster") else None,
            "communities": communities,
        }
    )
    with open(cache_path, "w") as f:
        f.write(payload)
    return communities


# ----------------------------------------------------------------------------- #
#                                NODE FEATURES                                  #
# ----------------------------------------------------------------------------- #

def load_global_features(dataset: str) -> pd.DataFrame:
    """Load the precomputed per-node global features (degree, centralities, ...)."""
    path = os.path.join(FEATURE_DIR, dataset, f"{dataset}_features.csv")
    df = pd.read_csv(path)
    return df.set_index("node")


def compute_community_features(graph: ig.Graph, communities: List[List[int]]) -> pd.DataFrame:
    """
    Compute community-relative node features for every node.

    Returns a DataFrame indexed by node id with columns:
        community_id, community_size, internal_degree, external_degree,
        internal_ratio, embeddedness, participation_coef
    """
    n = graph.vcount()
    node_comm = np.full(n, -1, dtype=int)
    comm_size = np.zeros(n, dtype=int)
    for cid, members in enumerate(communities):
        for v in members:
            node_comm[v] = cid
            comm_size[v] = len(members)

    adj = [set(graph.neighbors(v)) for v in range(n)]

    internal_deg = np.zeros(n, dtype=int)
    embeddedness = np.zeros(n, dtype=float)
    participation = np.zeros(n, dtype=float)

    for v in range(n):
        neigh = adj[v]
        deg = len(neigh)
        if deg == 0:
            continue
        same = [u for u in neigh if node_comm[u] == node_comm[v]]
        internal_deg[v] = len(same)

        # Embeddedness = local clustering restricted to same-community neighbours:
        # fraction of internal-neighbour pairs that are themselves connected.
        if len(same) >= 2:
            links = 0
            for i in range(len(same)):
                ai = adj[same[i]]
                for j in range(i + 1, len(same)):
                    if same[j] in ai:
                        links += 1
            embeddedness[v] = links / (len(same) * (len(same) - 1) / 2.0)

        # Participation coefficient (Guimera & Amaral): 1 - sum_c (k_ic/k_i)^2.
        # 0 -> all links inside one community (deeply embedded); ->1 spread across many.
        counts: Dict[int, int] = {}
        for u in neigh:
            counts[node_comm[u]] = counts.get(node_comm[u], 0) + 1
        participation[v] = 1.0 - sum((c / deg) ** 2 for c in counts.values())

    degree = np.array(graph.degree(), dtype=int)
    external_deg = degree - internal_deg
    with np.errstate(invalid="ignore", divide="ignore"):
        internal_ratio = np.where(degree > 0, internal_deg / degree, 0.0)

    return pd.DataFrame(
        {
            "community_id": node_comm,
            "community_size": comm_size,
            "internal_degree": internal_deg,
            "external_degree": external_deg,
            "internal_ratio": internal_ratio,
            "embeddedness": embeddedness,
            "participation_coef": participation,
        },
        index=pd.Index(range(n), name="node"),
    )


def build_node_feature_table(dataset: str, alg: str, graph: ig.Graph,
                             communities: List[List[int]]) -> pd.DataFrame:
    """Merge global and community-relative features into one per-node table."""
    glob = load_global_features(dataset)
    comm = compute_community_features(graph, communities)
    feat = comm.join(glob, how="left")
    # Keep degree from the graph (authoritative) but prefer CSV centralities.
    feat["degree"] = graph.degree()
    out_dir = os.path.join(OUT_DIR, dataset)
    check_dir(out_dir)
    feat.to_csv(os.path.join(out_dir, f"node_features_{alg}.csv"))
    return feat


# ----------------------------------------------------------------------------- #
#                                  OUTCOMES                                     #
# ----------------------------------------------------------------------------- #

def load_outcomes(dataset: str, alg: str) -> pd.DataFrame:
    """
    Load per-target-node success outcomes (``goal``) for every method, pooled across
    seeds and budget factors.

    Returns a long DataFrame: [target_node, method, seed, beta, goal].
    """
    rows = []
    for method, stem in METHOD_FILE.items():
        for seed in SEEDS:
            for beta in BETAS:
                path = os.path.join(
                    RUNS_DIR, f"seed_{seed}", dataset, alg, f"tau_{TAU}",
                    f"betaFactor_{beta}", "json_results", f"{stem}.json",
                )
                if not os.path.exists(path):
                    continue
                with open(path, "r") as f:
                    log = json.load(f)
                for node, goal in zip(log["target_node"], log["goal"]):
                    rows.append((int(node), method, seed, beta, int(goal)))
    return pd.DataFrame(rows, columns=["target_node", "method", "seed", "beta", "goal"])


def build_master_table(datasets: List[str], algs: List[str]) -> pd.DataFrame:
    """
    Assemble the full tidy table joining outcomes with node features for every
    (dataset, detection algorithm). One row per (dataset, alg, method, seed, beta,
    target_node).
    """
    frames = []
    for dataset in datasets:
        graph = import_graph(dataset)
        for alg in algs:
            try:
                communities = get_partition(dataset, alg, graph)
            except Exception as exc:  # pragma: no cover - environment dependent
                print(f"  [skip] could not get partition {dataset}/{alg}: {exc}")
                continue
            feat = build_node_feature_table(dataset, alg, graph, communities)
            outcomes = load_outcomes(dataset, alg)
            if outcomes.empty:
                print(f"  [skip] no outcomes for {dataset}/{alg}")
                continue
            merged = outcomes.join(feat, on="target_node")
            merged.insert(0, "detection_alg", alg)
            merged.insert(0, "dataset", dataset)
            frames.append(merged)
            print(f"  [table] {dataset}/{alg}: {len(merged)} rows")
    if not frames:
        raise RuntimeError("No data assembled - check that runs/partitions exist.")
    master = pd.concat(frames, ignore_index=True)
    master["method_name"] = master["method"].map(METHOD_RENAME)
    check_dir(OUT_DIR)
    master.to_csv(os.path.join(OUT_DIR, "master_table.csv"), index=False)
    return master


# ----------------------------------------------------------------------------- #
#                                   PLOTS                                       #
# ----------------------------------------------------------------------------- #

def _assign_groups(d: pd.DataFrame, feat: str, group_cols: List[str]) -> List[str]:
    """
    Add an integer ``bin`` column (1..3) to ``d`` and return the ordered x-tick labels.

    * ``community_size`` -> direct Small / Medium / Big split (always three sizes),
      using a dense rank of the size within each ``group_cols`` group.
    * every other feature -> percentile-rank groups Low (0-70%), Medium (70-90%),
      High (90-100%), the percentile rank being computed within each group.
    """
    if feat == "community_size":
        rank = d.groupby(group_cols)[feat].rank(method="dense")
        d["bin"] = rank.clip(upper=len(COMM_SIZE_LABELS))
        return COMM_SIZE_LABELS

    pct = d.groupby(group_cols)[feat].rank(pct=True)
    d["bin"] = pd.cut(
        pct, bins=PCT_BIN_EDGES, labels=[1, 2, 3], include_lowest=True
    ).astype("float")
    return PCT_BIN_LABELS


def plot_difficulty_curves(df: pd.DataFrame, features: List[tuple], title: str,
                           save_dir: str) -> None:
    """
    Success rate vs the three-group split of each feature, one line per method.
    One separate PDF per feature is written into ``save_dir``.
    """
    group_cols = ["dataset", "detection_alg"]
    check_dir(save_dir)

    for feat, label in features:
        d = df[["method_name", "goal", feat] + group_cols].copy()
        d = d.dropna(subset=[feat])
        tick_labels = _assign_groups(d, feat, group_cols)
        d = d.dropna(subset=["bin"])

        fig, ax = plt.subplots(figsize=(7.5, 5))
        sns.lineplot(
            data=d, x="bin", y="goal", hue="method_name",
            hue_order=METHOD_ORDER, palette=METHOD_PALETTE,
            estimator="mean", errorbar=("ci", 95), marker="o", ax=ax, legend=True,
        )
        ax.set_xlabel(label, fontsize=12)
        ax.set_ylabel("Success rate", fontsize=12)
        ax.set_ylim(-0.02, 1.02)
        ax.set_xticks(range(1, len(tick_labels) + 1))
        ax.set_xticklabels(tick_labels)
        for s in ax.spines.values():
            s.set_visible(True)
            s.set_color("black")
        ax.set_title(title, fontsize=12)
        ax.legend(loc="center left", bbox_to_anchor=(1.02, 0.5), frameon=False, fontsize=9)
        fig.savefig(os.path.join(save_dir, f"{feat}.pdf"), bbox_inches="tight", dpi=300)
        plt.close(fig)


def plot_nabla_feature_curves(df: pd.DataFrame, features: List[tuple], title: str,
                              save_dir: str) -> None:
    """
    Companion to the difficulty curves: a single plot for ``NABLA`` only, with one
    line per node characteristic (success rate vs the three-group split). Saved as
    ``{save_dir}/nabla_all_features.pdf``.

    Binning matches ``plot_difficulty_curves``: every feature is collapsed to three
    ordered groups (low -> high), so all characteristics share the same x positions.

    The raw values behind the plotted lines are also written next to the PDF as
    ``{save_dir}/nabla_all_features.json``. Because ``goal`` is binary, the per-group
    counts (``n`` / ``n_success``) fully describe the underlying values, plus the
    success rate and its dispersion (std / sem) so the curve can be reconstructed.
    """
    group_cols = ["dataset", "detection_alg"]
    check_dir(save_dir)

    nabla = df[df["method"] == "NABLA"]
    if nabla.empty:
        return

    parts = []
    palette = {}
    raw: Dict[str, object] = {"title": title, "method": "NABLA", "features": {}}
    for i, (feat, label) in enumerate(features):
        d = nabla[["goal", feat] + group_cols].copy()
        d = d.dropna(subset=[feat])
        tick_labels = _assign_groups(d, feat, group_cols)
        d = d.dropna(subset=["bin"])
        d["Characteristic"] = label
        parts.append(d[["bin", "goal", "Characteristic"]])
        palette[label] = FEATURE_LINE_COLORS[i % len(FEATURE_LINE_COLORS)]

        # Per-group raw values for the json sidecar.
        groups = []
        for b in sorted(d["bin"].dropna().unique()):
            goals = d.loc[d["bin"] == b, "goal"].astype(int)
            n = int(goals.size)
            n_success = int(goals.sum())
            idx = int(b) - 1
            grp_label = tick_labels[idx] if 0 <= idx < len(tick_labels) else str(int(b))
            groups.append({
                "bin": int(b),
                "label": grp_label.replace("\n", " "),
                "n": n,
                "n_success": n_success,
                "success_rate": (n_success / n) if n else None,
                "std": float(goals.std(ddof=1)) if n > 1 else 0.0,
                "sem": float(goals.std(ddof=1) / np.sqrt(n)) if n > 1 else 0.0,
            })
        raw["features"][label] = {"feature_key": feat, "groups": groups}

    with open(os.path.join(save_dir, "nabla_all_features.json"), "w") as f:
        json.dump(raw, f, indent=2)

    long_df = pd.concat(parts, ignore_index=True)

    fig, ax = plt.subplots(figsize=(7.5, 5))
    sns.lineplot(
        data=long_df, x="bin", y="goal", hue="Characteristic",
        hue_order=[lab for _, lab in features], palette=palette,
        estimator="mean", errorbar=("ci", 95), marker="o", ax=ax, legend=True,
    )
    ax.set_xlabel("Feature group (low → high)", fontsize=12)
    ax.set_ylabel("Success rate", fontsize=12)
    ax.set_ylim(-0.02, 1.02)
    ax.set_xticks([1, 2, 3])
    ax.set_xticklabels(["Low", "Medium", "High"])
    for s in ax.spines.values():
        s.set_visible(True)
        s.set_color("black")
    ax.set_title(rf"{title} — $\nabla$-CMH", fontsize=12)
    ax.legend(loc="center left", bbox_to_anchor=(1.02, 0.5), frameon=False, fontsize=9)
    fig.savefig(os.path.join(save_dir, "nabla_all_features.pdf"), bbox_inches="tight", dpi=300)
    plt.close(fig)


# ----------------------------------------------------------------------------- #
#                                   DRIVER                                      #
# ----------------------------------------------------------------------------- #

def make_all_plots(df: pd.DataFrame, features: List[tuple], algs: List[str]) -> None:
    """Generate per-dataset, pooled-per-algorithm and fully-pooled difficulty curves."""
    sns.set_theme(style="whitegrid")

    # --- per (dataset, detection algorithm) --- #
    for (dataset, alg), sub in df.groupby(["dataset", "detection_alg"]):
        base = os.path.join(OUT_DIR, dataset, alg)
        title = f"{dataset} — {alg}"
        plot_difficulty_curves(sub, features, title, base)
        plot_nabla_feature_curves(sub, features, title, base)

    # --- pooled across datasets, per detection algorithm --- #
    for alg, sub in df.groupby("detection_alg"):
        base = os.path.join(OUT_DIR, "all_datasets", alg)
        title = f"all datasets — {alg}"
        plot_difficulty_curves(sub, features, title, base)
        plot_nabla_feature_curves(sub, features, title, base)

    # --- fully pooled across datasets and detection algorithms --- #
    base = os.path.join(OUT_DIR, "all_datasets", "pooled")
    title = "all datasets & detection algorithms"
    plot_difficulty_curves(df, features, title, base)
    plot_nabla_feature_curves(df, features, title, base)


def main() -> None:
    parser = argparse.ArgumentParser(description="Target-node difficulty analysis.")
    parser.add_argument("--datasets", nargs="+", default=DATASETS, choices=DATASETS)
    parser.add_argument("--algs", nargs="+", default=DETECTION_ALGS, choices=DETECTION_ALGS)
    parser.add_argument("--extra-features", action="store_true",
                        help="Also analyse the extra features, not just the reviewer's five.")
    args = parser.parse_args()

    features = list(REVIEWER_FEATURES)
    if args.extra_features:
        features += EXTRA_FEATURES

    print(f"Datasets: {args.datasets}")
    print(f"Detection algorithms: {args.algs}")
    print("Building master table ...")
    master = build_master_table(args.datasets, args.algs)
    print(f"Master table: {len(master)} rows -> {os.path.join(OUT_DIR, 'master_table.csv')}")
    print("Generating plots ...")
    make_all_plots(master, features, args.algs)
    print(f"Done. Artefacts under {OUT_DIR}")


if __name__ == "__main__":
    main()
